const productList0=[
    {
      _id:0,
      img:"https://rukminim1.flixcart.com/image/612/612/kjym9ow0/rack-shelf/s/q/c/corner-shelf-bathroom-rack-shelf-adjd-original-imafzex2zzf9txq6.jpeg?q=70",
      title:"LURBA Corner Caddy Basket with Wall Mounted Plastic Wall Shelf Plastic, Steel Wall Shelf",
      ratting:3.8,
      totalRating:9,
      totoalReview:0,
      highlights:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
      originalPrice:999,
      discountPercentage:80,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    },
    {
      _id:1,
      img:"https://rukminim1.flixcart.com/image/612/612/kpydrbk0/soap-case/e/i/g/2-pc-multipurpose-kitchen-bathroom-shelf-wall-holder-storage-original-imag42mpgz9wq4rj.jpeg?q=70",
      title:"OFOY 2 PCS BATHROOM WALL SHELF ABS Plastic Multipurpose Kitchen Bathroom Wall Holder Storage Rack Corner Shelf bathroom corner",
      ratting:3.3,
      totalRating:60,
      totoalReview:10,
      highlights:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
      originalPrice:599,
      discountPercentage:61,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    },
    {
      _id:2,
      img:"https://rukminim1.flixcart.com/image/612/612/kr2e3680/rack-shelf/c/k/3/bathroom-accessories-shelves-corner-shower-shelf-wall-mounted-original-imag4xu8tyjwzey5.jpeg?q=70",
      title:"MFORALL Bathroom Accessories Shelves Corner Shower Shelf Wall-Mounted Nail-Free Glue Kitchen Bathroom Storage Rack Plastic Wall Shelf  (Number of Shelves - 2, Multicolor)",
      ratting:4.3,
      totalRating:0,
      totoalReview:0,
      highlights:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
      originalPrice:1499,
      discountPercentage:46,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    }
  ]
  const productList1=[
    {
      _id:3,
      img:"https://rukminim1.flixcart.com/image/660/792/xif0q/top/7/a/k/l-top4-textile-fab-original-imafkzgnjuatu8a2-bb.jpeg?q=50",
      title:"Casual Sleeveless Printed Women Dark Blue, White Top",
      ratting:3.7,
      totalRating:1031,
      totoalReview:92,
      highlights:["Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹1,500 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹1,500 and above","Bank Offer10% off on OneCard Credit Cards, up to ₹1,500. On orders of ₹1,500 and above","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022"],
      originalPrice:999,
      discountPercentage:70,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    },
    {
      _id:4,
      img:"https://rukminim1.flixcart.com/image/660/792/kcp4osw0/top/w/f/x/m-top111-textile-fab-original-imaftrrx5mzdtssn.jpeg?q=50",
      title:"Casual Regular Sleeves Striped Women Dark Blue, White Top",
      ratting:3.7,
      totalRating:542,
      totoalReview:45,
      highlights:["Special PriceGet extra 10% off (price inclusive of cashback/coupon)","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹1,500 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹1,500 and above","Bank Offer10% off on OneCard Credit Cards, up to ₹1,500. On orders of ₹1,500 and above"],
      originalPrice:999,
      discountPercentage:73,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    }
  ]
  const productList2=[
    {
      _id:5,
      img:"https://rukminim1.flixcart.com/image/660/792/k4rcmfk0pkrrdj/watch-refurbished/t/v/h/c-nf8976yl02j-sonata-original-imafnnnzbyxyeh7e.jpeg?q=50",
      title:"NF8976YL02J Analog Watch - For Women",
      ratting:4.2,
      totalRating:70634,
      totoalReview:8039,
      highlights:["Combo OfferBuy 2 items save 5%; Buy 3 or more save 10%See all products","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹1,500 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹1,500 and above","Bank Offer10% off on OneCard Credit Cards, up to ₹1,500. On orders of ₹1,500 and above"],
      originalPrice:670,
      discountPercentage:2,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    },
    {
      _id:6,
      img:"https://rukminim1.flixcart.com/image/660/792/k4rcmfk0pkrrdj/watch-refurbished/y/j/n/c-77085pp02-sonata-original-imafdcj5kwtkaywt.jpeg?q=50",
      title:"77085PP02 Volt Analog Watch - For Men",
      ratting:4.4,
      totalRating:700,
      totoalReview:1,
      highlights:["Combo OfferBuy 2 items save 5%; Buy 3 or more save 10%See all products","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹1,500 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹1,500 and above","Bank Offer10% off on OneCard Credit Cards, up to ₹1,500. On orders of ₹1,500 and above"],
      originalPrice:713,
      discountPercentage:2,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    }
  ]
  const productList3=[
    {
      _id:7,
      img:"https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/k/y/d/iphone-11-256-u-mwm82hn-a-apple-0-original-imafkg25mhaztxns.jpeg?q=70",
      title:"APPLE iPhone 11 (White, 64 GB)",
      ratting:4.6,
      totalRating:123,
      totoalReview:101,
      highlights:["64 GB ROM","15.49 cm (6.1 inch) Liquid Retina HD Display","12MP + 12MP | 12MP Front Camera","A13 Bionic Chip Processor","Brand Warranty of 1 Year"],
      originalPrice:49900,
      discountPercentage:15,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    },
    {
      _id:8,
      img:"https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/u/z/t/iphone-11-256-c-mwmd2hn-a-apple-0-original-imafkg24wszdhzy3.jpeg?q=70",
      title:"APPLE iPhone 11 (Green, 64 GB)",
      ratting:4.4,
      totalRating:123,
      totoalReview:101,
      highlights:["Suitable For: Living Room & Bedroom","Material: Plastic, Steel","No of Shelves: 1"],
      originalPrice:999,
      discountPercentage:80,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    }
  ]
  const productList4=[
    {
      _id:9,
      img:"https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/k/y/d/iphone-11-256-u-mwm82hn-a-apple-0-original-imafkg25mhaztxns.jpeg?q=70",
      title:"APPLE iPhone 11 (White, 64 GB)",
      ratting:4.6,
      totalRating:123,
      totoalReview:101,
      highlights:["64 GB ROM","15.49 cm (6.1 inch) Liquid Retina HD Display","12MP + 12MP | 12MP Front Camera","A13 Bionic Chip Processor","Brand Warranty of 1 Year"],
      originalPrice:49900,
      discountPercentage:15,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    },
    {
      _id:10,
      img:"https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/u/z/t/iphone-11-256-c-mwmd2hn-a-apple-0-original-imafkg24wszdhzy3.jpeg?q=70",
      title:"APPLE iPhone 11 (Green, 64 GB)",
      ratting:4.4,
      totalRating:123,
      totoalReview:101,
      highlights:["Suitable For: Living Room & Bedroom","Material: Plastic, Steel","No of Shelves: 1"],
      originalPrice:999,
      discountPercentage:80,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    }
  ]
  const productList5=[
    {
      _id:11,
      img:"https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/k/y/d/iphone-11-256-u-mwm82hn-a-apple-0-original-imafkg25mhaztxns.jpeg?q=70",
      title:"APPLE iPhone 11 (White, 64 GB)",
      ratting:4.6,
      totalRating:123,
      totoalReview:101,
      highlights:["64 GB ROM","15.49 cm (6.1 inch) Liquid Retina HD Display","12MP + 12MP | 12MP Front Camera","A13 Bionic Chip Processor","Brand Warranty of 1 Year"],
      originalPrice:49900,
      discountPercentage:15,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    },
    {
      _id:12,
      img:"https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/u/z/t/iphone-11-256-c-mwmd2hn-a-apple-0-original-imafkg24wszdhzy3.jpeg?q=70",
      title:"APPLE iPhone 11 (Green, 64 GB)",
      ratting:4.4,
      totalRating:123,
      totoalReview:101,
      highlights:["Suitable For: Living Room & Bedroom","Material: Plastic, Steel","No of Shelves: 1"],
      originalPrice:999,
      discountPercentage:80,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    }
  ]
  const productList6=[
    {
      _id:13,
      img:"https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/k/y/d/iphone-11-256-u-mwm82hn-a-apple-0-original-imafkg25mhaztxns.jpeg?q=70",
      title:"APPLE iPhone 11 (White, 64 GB)",
      ratting:4.6,
      totalRating:123,
      totoalReview:101,
      highlights:["64 GB ROM","15.49 cm (6.1 inch) Liquid Retina HD Display","12MP + 12MP | 12MP Front Camera","A13 Bionic Chip Processor","Brand Warranty of 1 Year"],
      originalPrice:49900,
      discountPercentage:15,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    },
    {
      _id:14,
      img:"https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/u/z/t/iphone-11-256-c-mwmd2hn-a-apple-0-original-imafkg24wszdhzy3.jpeg?q=70",
      title:"APPLE iPhone 11 (Green, 64 GB)",
      ratting:4.4,
      totalRating:123,
      totoalReview:101,
      highlights:["Suitable For: Living Room & Bedroom","Material: Plastic, Steel","No of Shelves: 1"],
      originalPrice:999,
      discountPercentage:80,
      isDeleverable:true,
      offers:["Partner OfferBuy this product and get upto ₹250 off on Flipkart Furniture","Partner OfferPurchase this product & win a surprise cashback coupon for The Big Billion Days Sale 2022","Bank Offer10% off on Citi Credit and Debit Cards, up to ₹3,000. On orders of ₹5,000 and above","Bank Offer10% off on Bank of Baroda Credit Cards, up to ₹1,500. On orders of ₹5,000 and above"],
    }
  ]

  const allProducts=[...productList0,...productList1,...productList2,...productList3,...productList4,...productList5,...productList6]

  export {productList0,productList1,productList2,productList3,productList4,productList5,productList6,allProducts}